export const experienceContent = {
  heading: "Skills",
  skills: [
    "HTML5",
    "CSS",
    "Tailwind CSS",
    "SCSS",
    "Javascript",
    "Typescript",
    "Python",
    "Node JS",
    "React Js",
    "Redux",
    "Next Js",
    "Mongo DB",
    "Prisma",
    "Git",
    "Framer Motion",
  ],
};
